nginx:
   image: "nginx:latest"
   ports:
     - 10001:443
   links:
     - registry_auth:registry_auth
   volumes:
     #- ./nginx/:/etc/nginx/conf.d:ro
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./nginx/registry.conf:/etc/nginx/conf.d/registry.conf:ro
   restart: always


registry_auth:
    image: registry:2.5.0
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./data:/var/lib/registry
    restart: always
